#:schema https://schemas.spinframework.dev/spin/manifest-v2/latest.json

spin_manifest_version = 2

[application]
name = "spin-image-classification-demo"
version = "0.1.0"
authors = ["Karthik Ganeshram <karthik.ganeshram@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/api/..."
component = "spin-image-classification-demo"

[[trigger.http]]
route = "/..."
component = "frontend"


[component.frontend]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "frontend", destination = "/" }]

[component.spin-image-classification-demo]
source = "target/wasm32-wasip1/release/spin_image_classification_demo.wasm"
allowed_outbound_hosts = []
[component.spin-image-classification-demo.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
